# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('student', models.ManyToManyField(to='lab3_db.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(choices=[('T', 'Toronto'), ('W', 'Windsor'), ('L', 'London')], default='W', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_db.Book'),
        ),
    ]
