# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_db', '0002_auto_20170516_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
