# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_db', '0004_auto_20170518_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(choices=[(' ', '---'), ('T', 'Toronto'), ('W', 'Windsor')], default='---', max_length=20),
        ),
    ]
