# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_db', '0005_auto_20170518_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ManyToManyField(to='lab3_db.Course'),
        ),
    ]
