# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_db', '0007_auto_20170521_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
