# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(choices=[(' ', '---'), ('T', 'Toronto'), ('W', 'Windsor')], default='---', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Book'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ManyToManyField(to='myapp.Course'),
        ),
    ]
