# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170618_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True)),
                ('age', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
