# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default=0, validators=[myapp.models.validate_num]),
        ),
    ]
